TheCocktail.Web/Models/ErrorResult.cs
namespace TheCocktail.Web.Models
{
    public class ErrorResult
    {
        public List<string> Messages { get; set; } = new();

        public string? Source { get; set; }
        public string? Exception { get; set; }
        public string? ErrorId { get; set; }
        public string? SupportMessage { get; set; }
        public int StatusCode { get; set; }
    }
}

TheCocktail.Web/Controllers/CocktailsController.cs
using Microsoft.AspNetCore.Mvc;
using TheCocktail.Application.DTOs.Cocktails;
using TheCocktail.Application.Features.Cocktails;

namespace TheCocktail.Web.Controllers
{
    public class CocktailsController : Controller
    {
        private readonly ICocktailService _cocktailService;

        private const int USER_TEST = 1;

        public CocktailsController(
            ICocktailService cocktailService
        )
        {
            _cocktailService = cocktailService ?? throw new ArgumentNullException(nameof(cocktailService));
        }

        public IActionResult Index()
        {

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> SearchCocktails(SearchCocktailsDTO searchViewModel)
            =>  View(await _cocktailService.GetCocktailsByNameOrIngredient(searchViewModel));

        [HttpGet]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> Detail(string cocktailId)
            => View(await _cocktailService.GetCocktailDetail(USER_TEST, cocktailId));
    }
}

TheCocktail.Web/Controllers/FavoriteCocktailsController.cs
using Microsoft.AspNetCore.Mvc;
using TheCocktail.Application.Features.Favorites;
using TheCocktail.Common.Responses;
using TheCocktail.Domain.Entities;

namespace TheCocktail.Web.Controllers
{
    public class FavoriteCocktailsController : Controller
    {
        private readonly IFavoriteService _favoriteService;
        private const int USER_TEST = 1;

        public FavoriteCocktailsController(IFavoriteService favoriteService)
        {
            _favoriteService = favoriteService ?? throw new ArgumentNullException(nameof(favoriteService));
        }

        [HttpPost]
        public async Task<IActionResult> AddRemoveFavorite(Favorite favorite)
        {
            BaseCommandResponse response;

            if (favorite.FavoriteId == 0)
            {
                favorite.UserId = USER_TEST;
                response = await _favoriteService.AddFavorite(favorite);
            }
            else
            {
                response = await _favoriteService.RemoveFavorite(new Domain.Entities.Favorite
                {
                    FavoriteId = favorite.FavoriteId
                });
            }

            return new OkObjectResult(response);
        }

        public async Task<IActionResult> ListFavorites()
            => View(await _favoriteService.GetFavoritesByUserId(USER_TEST));
    }
}

TheCocktail.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace TheCocktail.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(
            ILogger<HomeController> logger
        )
        {
            _logger = logger;
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View();
        }
    }
}

TheCocktail.Web/Views/Cocktails/Detail.cshtml
@model CocktailDetailDTO

@{
    var cocktailDetail = Model.CocktailDetail?.drinks.FirstOrDefault();
}

<div aria-live="polite" aria-atomic="true" class="d-flex justify-content-center align-items-center w-100">
    <div id="notiFavorites" data-delay="4000" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-body">
            <div class="d-flex">
                <strong class="mr-auto p-2 notiFavoritesTitle"></strong>
                <a class="p-2 btn btn-outline-dark goFavorites" id="btnGoFavorites"
                   asp-action="ListFavorites" asp-controller="FavoriteCocktails">Ver</a>
            </div>
        </div>
    </div>
</div>


<section class="detail">

    @if (cocktailDetail is null)
    {
        <h1><strong>Información del cóctel</strong></h1>
        <h2>
            <p>No se encontro información del cóctel</p>
        </h2>
    }
    else
    {
        <div class="row">
            <div class="col-md-6">
                <h2 class="drink-title">
                    @cocktailDetail.strDrink
                    <a id="btnAddFavorite"
                       data-drinkname="@cocktailDetail.strDrink"
                       data-drinkimage="@cocktailDetail.strDrinkThumb"
                       data-favoriteid="@(Model.FavoriteInformation.IsFavorite ? Model.FavoriteInformation.FavoriteId : 0)"
                       data-drinkid="@cocktailDetail.idDrink" 
                       href="#"
                       title="@(Model.FavoriteInformation.IsFavorite ? "Quitar de favoritos" : "Agregar a favoritos")">
                        <i id="icon-favorite"
                           class="bi @(Model.FavoriteInformation.IsFavorite ? "bi-heart-fill" : "bi-heart") bi-heart-red"></i>
                    </a>
                </h2>
                <img src="@cocktailDetail.strDrinkThumb" width="90%" />
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <h3 class="ingredients-title">Ingredientes</h3>
                    </div>
                    @foreach (var ingredient in cocktailDetail.getIngredients())
                    {
                        @if (!string.IsNullOrEmpty(ingredient.Item1))
                        {
                            <div class="col-md-4 text-center">
                                <img class="img-fluid" src="@ingredient.Item2" />
                                <p>@(ingredient.Item1)</p>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <h3 class="instructions-title">Instrucciones</h3>
                <p>
                    @cocktailDetail.strInstructions
                </p>
            </div>
        </div>
    }
</section>

@section Scripts {
    <script src="~/js/app/cocktails.js" asp-append-version="true"></script>
}

TheCocktail.Web/Views/Cocktails/Index.cshtml
@model SearchCocktailsDTO

@{
    ViewData["Title"] = "Home Page";
}

<div class="jumbotron">
    <h1 class="display-4 text-center"><b>Bienvenidos</b></h1>
    <p class="lead">
        <strong>
            En el mundo de la coctelería siempre encontrarás un coctel delicioso para cada tipo de persona. Encontrarás una enorme cantidad de propuestas que son totalmente perfectas para brindar con amigos, familiares y con tu pareja.
        </strong>
    </p>
    <p>
        En nuestro listado de cocteles exquisitos encontrarás desde los clásicos, como el Mojito o el Cosmopolitan, hasta los tragos más innovadores. Es por eso que queremos compartir contigo nuestra selección de recetas para cocteles, para que triunfes en tus quedadas con amigos o en tus reuniones familiares. ¡Porque nada triunfa más que preparar deliciosos cocteles tras una buena cena!
    </p>
</div>

<section class="busqueda-cocteles">

    <form asp-action="SearchCocktails" method="get" class="d-flex justify-content-center flex-nowrap">
        <div class="form-row align-items-center">
            <div class="col-sm-6">
                <input asp-for="Search" type="text" class="form-control" id="txtBuscarCocktail" placeholder="Buscar por Coctel o Ingrediente...">
            </div>
            <div class="col-sm-3">
                <select asp-for="TipoBusqueda" class="form-control mr-sm-2" id="ddlTipoBusqueda">
                    <option value="1">Por nombre</option>
                    <option value="2">Por ingrediente</option>
                </select>
            </div>
            <div class="col-sm-3">
                <button type="submit" class="btn btn-primary">
                    Buscar <i class="bi bi-search"></i>
                </button>
            </div>
        </div>
    </form>
</section>

TheCocktail.Web/Views/Cocktails/SearchCocktails.cshtml
@model CocktailDbDTO

<section class="list-cocktails">
    <h1>Cócteles</h1>
    @if (Model.drinks.Any())
    {
        <div class="center">
            <div class="row">
                @foreach (var cocktail in Model.drinks)
                {
                    @await Html.PartialAsync("_CocktailItem", cocktail)
                }
            </div>
        </div>
    }
    else
    {
        <h2>
            No se encontró información para la búsqueda
        </h2>
    }
</section>

TheCocktail.Web/Views/Cocktails/_CocktailItem.cshtml
@model DrinkDTO

<div class="col-md-3">
    <a asp-action="Detail" asp-route-cocktailId="@Model.idDrink" class="cocktail-item">
        <div>
            <img src="@Model.strDrinkThumb" width="95%" />
        </div>
        <p class="text-center">@Model.strDrink</p>
    </a>
</div>

TheCocktail.Web/Views/FavoriteCocktails/ListFavorites.cshtml
@model List<Favorite>

<section id="listFavorites">
    <div class="row">
        <div class="col-md-12">
            <h1>
                Tus cócteles favoritos
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <span class="lead">
                <strong id="totalFavorites">@(Model.Count == 1 ? "1 cóctel" : $"{Model.Count} cócteles")</strong>
            </span>
            <hr />
        </div>
    </div>
    @if (Model.Any())
    {
        foreach (var favorite in Model)
        {
            @await Html.PartialAsync("_FavoriteItem", favorite)
        }
    }
</section>

<div id="modalConfirmRemove" class="modal" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Eliminar favorito</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>¿Confirmas que quieres eliminar este cóctel de tu lista?</p>
            </div>
            <div class="modal-footer text-center">
                <button type="button" class="btn btn-lg btn-primary" id="btnConfirmRemove">Confirmar</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/js/app/favorite.js" asp-append-version="true"></script>
}

TheCocktail.Web/Views/FavoriteCocktails/_FavoriteItem.cshtml
@model Favorite

<div class="media media-favorite mt-3">
    <a asp-controller="Cocktails" asp-action="Detail" asp-route-cocktailId="@Model.DrinkId">
        <img class="align-self-start mr-1" src="@Model.DrinkImage" alt="@Model.DrinkName">
    </a>
    <div class="media-body">
        <h5 class="mt-0">@Model.DrinkName</h5>
        <button type="button" class="btn btn-danger btnRemoveFavorite" data-favoriteid="@Model.FavoriteId">
            Eliminar
        </button>
    </div>
</div>

TheCocktail.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>The Cocktail Site</title>
    <environment include="Development">
        <link href="~/css/bootstrap/css/bootstrap.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link href="~/css/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/css/site.min.css" rel="stylesheet" />
    </environment>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/TheCocktail.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav id="menu-main" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Cocktails" asp-action="Index">
                    <img src="~/img/logo.png" alt="" />
                </a>
                <button class="navbar-toggler" style="background: #fff" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Cocktails" asp-action="Index">
                                Bienvenido 
                                <i class="bi bi-house"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="FavoriteCocktails" asp-action="ListFavorites">
                                Tus favoritos 
                                <i class="bi bi-heart"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" id="main-container">
        <main id="main" role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TheCocktail.Web
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/css/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>